#!/bin/bash
while read oldrev newrev refname
do
  branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ "master" == "$branch" ]; then
      set -e
      export PATH=$PATH:/usr/local/bin
      export NVM_DIR="$HOME/.nvm"

      . ~/.nvm/nvm.sh
      kolony build <%= name %>
    fi
done
